version: "3"
services:
  php:
    restart: always
    container_name: sidefs-php
    build: ./php
    # image: php:8.1-fpm-alpine
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./app/config.php:/var/app/config.php"
      - "${PROJECT_PATH}:/var/app/backend"
    working_dir: /var/app/backend
    dns:
      - ${DNS-8.8.8.8}
    networks:
      - sidefs
  nginx:
    restart: always
    container_name: sidefs-nginx
    image: nginx:1.23-alpine
    environment:
      TZ: Asia/Shanghai
    ports:
      - '5000:5000'
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sidefs
  redis:
    restart: always
    container_name: sidefs-redis
    image: redis:7.0-alpine
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - sidefs
networks:
  sidefs:
    driver: bridge